--
-- PostgreSQL database cluster dump
--

\restrict vWjUrf8N5HEClg4CVF4Vzv5jzVnNzkb18nX41VlwldXfpq5rCY6bjCgdP6qeTpb

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'md5ccc03c0d8bea2d272943a74e541219cf';






\unrestrict vWjUrf8N5HEClg4CVF4Vzv5jzVnNzkb18nX41VlwldXfpq5rCY6bjCgdP6qeTpb

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict BF4Vef3hnkXfb2zh66LZY9Tmpi3eZIUG7DRjWfHIRkNLfPNjYSzdFWQ8WQrkcGJ

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict BF4Vef3hnkXfb2zh66LZY9Tmpi3eZIUG7DRjWfHIRkNLfPNjYSzdFWQ8WQrkcGJ

--
-- Database "db_inventario" dump
--

--
-- PostgreSQL database dump
--

\restrict 9ZPc05UOAFTfj5TJf47h9EQWn0DMCBr0JtPmIBHjpxlbHxfMgZ5jRpcyfLn8Rg0

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: db_inventario; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_inventario WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE db_inventario OWNER TO postgres;

\unrestrict 9ZPc05UOAFTfj5TJf47h9EQWn0DMCBr0JtPmIBHjpxlbHxfMgZ5jRpcyfLn8Rg0
\connect db_inventario
\restrict 9ZPc05UOAFTfj5TJf47h9EQWn0DMCBr0JtPmIBHjpxlbHxfMgZ5jRpcyfLn8Rg0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: configuracion_inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.configuracion_inventario (
    clave text NOT NULL,
    valor text
);


ALTER TABLE public.configuracion_inventario OWNER TO postgres;

--
-- Name: lotes_inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lotes_inventario (
    id_lote integer NOT NULL,
    id_almacen integer NOT NULL,
    id_item integer NOT NULL,
    cantidad_inicial numeric(10,2) NOT NULL,
    cantidad_disponible numeric(10,2) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    fecha_entrada timestamp without time zone NOT NULL,
    fecha_salida timestamp without time zone,
    fecha_vencimiento date,
    metodo_valuacion text,
    estado text,
    referencia_id integer,
    referencia_tipo text
);


ALTER TABLE public.lotes_inventario OWNER TO postgres;

--
-- Name: lotes_inventario_id_lote_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lotes_inventario ALTER COLUMN id_lote ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lotes_inventario_id_lote_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos_inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos_inventario (
    id_movimiento integer NOT NULL,
    id_lote integer,
    id_almacen integer NOT NULL,
    id_item integer NOT NULL,
    tipo_movimiento text,
    cantidad numeric(10,2) NOT NULL,
    costo_unitario numeric(10,2) NOT NULL,
    costo_total numeric(10,2) NOT NULL,
    fecha_movimiento timestamp without time zone NOT NULL,
    id_empleado integer,
    referencia_id integer,
    referencia_tipo text
);


ALTER TABLE public.movimientos_inventario OWNER TO postgres;

--
-- Name: movimientos_inventario_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos_inventario ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_inventario_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: traspasos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.traspasos (
    id_traspaso integer NOT NULL,
    id_almacen_origen integer NOT NULL,
    id_almacen_destino integer NOT NULL,
    id_empleado integer NOT NULL,
    fecha_solicitud timestamp without time zone NOT NULL,
    fecha_aprobacion timestamp without time zone,
    estado text,
    observaciones text
);


ALTER TABLE public.traspasos OWNER TO postgres;

--
-- Name: traspasos_almacen_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.traspasos_almacen_item (
    id_traspaso_item integer NOT NULL,
    id_traspaso integer NOT NULL,
    id_item integer NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    id_lote_origen integer,
    id_lote_destino integer
);


ALTER TABLE public.traspasos_almacen_item OWNER TO postgres;

--
-- Name: traspasos_almacen_item_id_traspaso_item_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.traspasos_almacen_item ALTER COLUMN id_traspaso_item ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.traspasos_almacen_item_id_traspaso_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: traspasos_id_traspaso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.traspasos ALTER COLUMN id_traspaso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.traspasos_id_traspaso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: configuracion_inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.configuracion_inventario (clave, valor) FROM stdin;
\.


--
-- Data for Name: lotes_inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lotes_inventario (id_lote, id_almacen, id_item, cantidad_inicial, cantidad_disponible, precio_unitario, fecha_entrada, fecha_salida, fecha_vencimiento, metodo_valuacion, estado, referencia_id, referencia_tipo) FROM stdin;
45	1	8	400.00	400.00	12.00	2025-01-15 10:05:05	\N	2026-12-12	PEPS	disponible	1	compra
49	2	11	200.00	161.00	11.00	2025-01-15 10:02:33	2025-05-01 16:48:54	2029-12-12	PEPS	disponible	2	compra
50	2	12	100.00	0.00	12.00	2025-01-15 10:02:33	2025-05-01 10:10:51	2028-12-12	PEPS	consumido	2	compra
54	3	5	66.00	57.00	0.00	2025-02-01 10:05:06	2025-05-01 10:02:25	2029-12-12	PEPS	disponible	5	produccion
56	2	13	150.00	140.00	10.00	2025-02-01 10:08:22	2026-05-27 16:11:02	2026-05-31	PEPS	disponible	4	compra
58	2	14	100.00	100.00	15.00	2025-02-01 10:17:29	\N	2026-07-12	PEPS	disponible	5	compra
59	2	9	50.00	41.00	25.00	2025-02-01 10:17:29	2025-05-01 16:53:44	2026-10-30	PEPS	disponible	5	compra
60	2	13	121.00	121.00	12.00	2026-05-27 16:05:22	\N	2028-12-12	PEPS	disponible	6	compra
61	4	9	213.00	213.00	21.00	2026-05-27 16:05:51	\N	2028-12-12	PEPS	disponible	7	compra
62	5	6	120.00	120.00	0.00	2026-05-27 16:10:40	\N	2028-12-12	PEPS	disponible	9	produccion
63	5	6	90.00	90.00	0.00	2026-05-27 16:11:03	\N	\N	PEPS	disponible	7	produccion
64	5	5	5.00	0.00	0.00	2026-05-27 16:11:16	2025-05-01 10:16:05	\N	PEPS	consumido	3	produccion
65	2	10	222.00	201.00	12.00	2025-05-01 10:04:56	2025-05-01 16:53:44	2026-12-12	PEPS	disponible	8	compra
66	2	13	12.00	12.00	12.00	2025-05-01 10:04:56	\N	2027-12-12	PEPS	disponible	8	compra
67	2	8	222.00	210.00	12.00	2025-05-01 10:06:35	2025-05-01 16:53:44	2027-02-12	PEPS	disponible	9	compra
68	2	13	122.00	122.00	12.00	2025-05-01 10:06:35	\N	2028-08-12	PEPS	disponible	9	compra
69	2	12	12.00	7.00	121.00	2025-05-01 10:07:04	2025-05-01 16:48:54	2028-02-09	PEPS	disponible	10	compra
71	4	5	88.00	88.00	0.00	2025-05-01 10:10:51	\N	2027-12-12	PEPS	disponible	11	produccion
72	4	10	10.00	10.00	0.00	2025-05-01 13:10:11	\N	\N	PEPS	disponible	2	traspaso
73	4	10	10.00	10.00	12.00	2025-05-01 10:04:56	\N	2026-12-12	PEPS	disponible	2	traspaso
75	6	7	5.00	5.00	0.00	2025-05-01 16:53:15	\N	2026-08-30	UEPS	disponible	14	produccion
77	2	13	123.00	123.00	23.00	2025-05-01 17:00:29	\N	2026-06-01	PEPS	disponible	11	compra
78	2	14	321.00	321.00	12.00	2025-05-01 17:07:29	\N	2026-05-31	PEPS	disponible	12	compra
79	2	12	4.00	4.00	3.30	2026-07-07 13:42:24.662828	\N	2026-07-06	PEPS	Disponible	\N	\N
91	3	4	40.00	40.00	0.00	2026-07-08 18:03:27.073444	\N	2026-07-24	PEPS	Disponible	\N	\N
57	3	6	90.00	50.00	0.00	2025-02-01 10:11:07	2026-05-27 16:04:52	2029-10-10	PEPS	disponible	8	produccion
80	5	6	20.00	20.00	0.00	2026-07-07 18:21:17.98828	\N	2029-10-10	PEPS	Disponible	\N	\N
70	5	2	75.00	50.00	0.00	2025-05-01 10:08:25	\N	2027-12-12	PEPS	disponible	10	produccion
74	5	3	21.00	0.00	0.00	2025-05-01 16:48:54	2026-07-07 21:08:40.647546	\N	UEPS	Agotado	12	produccion
46	2	8	200.00	99.00	12.00	2025-01-15 10:02:33	2025-05-01 10:10:51	2026-12-12	PEPS	disponible	2	compra
76	5	7	5.00	0.00	0.00	2025-05-01 16:53:44	2026-07-07 21:30:05.258566	\N	UEPS	Agotado	13	produccion
82	2	8	22.00	22.00	1.40	2026-07-07 21:45:42.095962	\N	2029-12-12	PEPS	Disponible	\N	\N
83	2	9	10.00	10.00	83.30	2026-07-08 01:45:26.283373	\N	\N	PEPS	Disponible	\N	\N
52	2	12	20.00	7.00	5.98	2025-01-15 10:15:20	2025-05-01 10:10:51	2026-08-30	PEPS	disponible	3	compra
92	5	4	20.00	20.00	0.00	2026-07-08 21:25:00.778586	\N	2026-07-09	PEPS	Disponible	\N	\N
55	3	2	100.00	70.00	0.00	2025-02-01 10:05:52	2025-05-01 10:13:55	2029-12-12	PEPS	disponible	6	produccion
81	6	2	25.00	5.00	0.00	2026-07-07 18:22:12.570242	\N	2027-12-12	PEPS	Disponible	\N	\N
48	2	10	200.00	105.00	1.00	2025-01-15 10:02:33	2025-05-01 13:10:11	2027-12-12	PEPS	disponible	2	compra
86	4	10	10.00	10.00	1.00	2026-07-08 13:56:08.831138	\N	2027-12-12	PEPS	Disponible	\N	\N
87	3	4	40.00	40.00	0.00	2026-07-08 14:52:46.842517	\N	2026-07-29	PEPS	Disponible	\N	\N
88	2	14	100.00	100.00	15.00	2026-07-08 16:54:05.850813	\N	2026-07-16	PEPS	Disponible	\N	\N
84	2	4	20.00	18.00	0.00	2026-07-08 01:51:15.631917	\N	2026-07-10	PEPS	Disponible	\N	\N
85	2	2	20.00	18.00	0.00	2026-07-08 12:08:46.204171	\N	2027-12-12	PEPS	Disponible	\N	\N
47	2	9	200.00	78.00	32.00	2025-01-15 10:02:33	2025-05-01 10:10:51	2028-12-12	PEPS	disponible	2	compra
89	4	9	22.00	22.00	32.00	2026-07-08 16:54:59.079194	\N	2028-12-12	PEPS	Disponible	\N	\N
93	1	2	1.00	1.00	0.00	2026-07-08 22:41:12.938375	\N	2029-12-12	PEPS	Disponible	\N	\N
53	3	3	84.00	77.00	0.00	2025-02-01 10:04:12	2026-05-27 13:40:36	2027-12-12	PEPS	disponible	4	produccion
51	3	4	40.00	24.00	0.00	2025-01-15 10:09:41	2025-05-01 10:02:25	\N	PEPS	disponible	2	produccion
90	1	8	10.00	10.00	18.50	2026-07-08 18:02:09.431499	\N	2026-07-10	PEPS	Disponible	\N	\N
\.


--
-- Data for Name: movimientos_inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimientos_inventario (id_movimiento, id_lote, id_almacen, id_item, tipo_movimiento, cantidad, costo_unitario, costo_total, fecha_movimiento, id_empleado, referencia_id, referencia_tipo) FROM stdin;
11	\N	1	8	ingreso	400.00	12.00	4800.00	2025-01-15 10:05:05	1	1	compra
12	\N	2	8	ingreso	200.00	12.00	2400.00	2025-01-15 10:02:33	1	2	compra
13	\N	2	9	ingreso	200.00	32.00	6400.00	2025-01-15 10:02:33	1	2	compra
14	\N	2	10	ingreso	200.00	1.00	200.00	2025-01-15 10:02:33	1	2	compra
15	\N	2	11	ingreso	200.00	11.00	2200.00	2025-01-15 10:02:33	1	2	compra
16	\N	2	12	ingreso	100.00	12.00	1200.00	2025-01-15 10:02:33	1	2	compra
17	\N	2	8	egreso	-25.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
18	\N	2	9	egreso	-15.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
19	\N	2	10	egreso	-25.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
20	\N	2	11	egreso	-20.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
21	\N	2	12	egreso	-5.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
22	\N	3	4	ingreso	40.00	0.00	0.00	2025-01-15 10:09:41	1	2	produccion
23	\N	2	12	ingreso	20.00	5.98	119.60	2025-01-15 10:15:20	1	3	compra
24	\N	2	8	egreso	-8.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
25	\N	2	9	egreso	-12.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
26	\N	2	10	egreso	-4.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
27	\N	2	11	egreso	-4.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
28	\N	2	12	egreso	-20.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
29	\N	3	3	ingreso	84.00	0.00	0.00	2025-02-01 10:04:12	1	4	produccion
30	\N	2	8	egreso	-9.00	0.00	0.00	2025-02-01 10:05:06	1	5	produccion
31	\N	2	9	egreso	-9.00	0.00	0.00	2025-02-01 10:05:06	1	5	produccion
32	\N	2	10	egreso	-3.00	0.00	0.00	2025-02-01 10:05:06	1	5	produccion
33	\N	2	12	egreso	-12.00	0.00	0.00	2025-02-01 10:05:06	1	5	produccion
34	\N	3	5	ingreso	66.00	0.00	0.00	2025-02-01 10:05:06	1	5	produccion
35	\N	2	9	egreso	-4.00	0.00	0.00	2025-02-01 10:05:52	1	6	produccion
36	\N	2	10	egreso	-8.00	0.00	0.00	2025-02-01 10:05:52	1	6	produccion
37	\N	2	11	egreso	-8.00	0.00	0.00	2025-02-01 10:05:52	1	6	produccion
38	\N	2	12	egreso	-16.00	0.00	0.00	2025-02-01 10:05:52	1	6	produccion
39	\N	3	2	ingreso	100.00	0.00	0.00	2025-02-01 10:05:52	1	6	produccion
40	\N	2	13	ingreso	150.00	10.00	1500.00	2025-02-01 10:08:22	1	4	compra
41	\N	2	8	egreso	-6.00	0.00	0.00	2025-02-01 10:11:07	1	8	produccion
42	\N	2	9	egreso	-9.00	0.00	0.00	2025-02-01 10:11:07	1	8	produccion
43	\N	2	10	egreso	-6.00	0.00	0.00	2025-02-01 10:11:07	1	8	produccion
44	\N	2	13	egreso	-3.00	0.00	0.00	2025-02-01 10:11:07	1	8	produccion
45	\N	3	6	ingreso	90.00	0.00	0.00	2025-02-01 10:11:07	1	8	produccion
46	\N	3	4	egreso	-10.00	41.00	-410.00	2025-02-01 10:13:32	1	1	venta
47	\N	3	5	egreso	-6.00	8.00	-48.00	2025-02-01 10:13:53	1	2	venta
48	\N	3	6	egreso	-15.00	2.00	-30.00	2025-02-01 10:14:20	1	3	venta
49	\N	2	14	ingreso	100.00	15.00	1500.00	2025-02-01 10:17:29	1	5	compra
50	\N	2	9	ingreso	50.00	25.00	1250.00	2025-02-01 10:17:29	1	5	compra
51	\N	3	2	egreso	-12.00	1.00	-12.00	2026-05-27 16:03:23	1	9	venta
52	\N	3	6	egreso	-5.00	2.00	-10.00	2026-05-27 16:04:52	1	10	venta
53	\N	2	13	ingreso	121.00	12.00	1452.00	2026-05-27 16:05:22	1	6	compra
54	\N	4	9	ingreso	213.00	21.00	4473.00	2026-05-27 16:05:51	1	7	compra
55	\N	2	8	egreso	-8.00	0.00	0.00	2026-05-27 16:10:40	1	9	produccion
56	\N	2	9	egreso	-12.00	0.00	0.00	2026-05-27 16:10:40	1	9	produccion
57	\N	2	10	egreso	-8.00	0.00	0.00	2026-05-27 16:10:40	1	9	produccion
58	\N	2	13	egreso	-4.00	0.00	0.00	2026-05-27 16:10:40	1	9	produccion
59	\N	5	6	ingreso	120.00	0.00	0.00	2026-05-27 16:10:40	1	9	produccion
60	\N	2	8	egreso	-6.00	0.00	0.00	2026-05-27 16:11:02	1	7	produccion
61	\N	2	9	egreso	-9.00	0.00	0.00	2026-05-27 16:11:02	1	7	produccion
62	\N	2	10	egreso	-6.00	0.00	0.00	2026-05-27 16:11:02	1	7	produccion
63	\N	2	13	egreso	-3.00	0.00	0.00	2026-05-27 16:11:03	1	7	produccion
64	\N	5	6	ingreso	90.00	0.00	0.00	2026-05-27 16:11:03	1	7	produccion
65	\N	2	8	egreso	-15.00	0.00	0.00	2026-05-27 16:11:16	1	3	produccion
66	\N	2	9	egreso	-15.00	0.00	0.00	2026-05-27 16:11:16	1	3	produccion
67	\N	2	10	egreso	-5.00	0.00	0.00	2026-05-27 16:11:16	1	3	produccion
68	\N	2	12	egreso	-20.00	0.00	0.00	2026-05-27 16:11:16	1	3	produccion
69	\N	5	5	ingreso	5.00	0.00	0.00	2026-05-27 16:11:16	1	3	produccion
70	\N	3	5	egreso	-3.00	8.00	-24.00	2025-05-01 10:02:25	1	11	venta
71	\N	3	4	egreso	-2.00	40.00	-80.00	2025-05-01 10:02:25	1	11	venta
72	\N	2	10	ingreso	222.00	12.00	2664.00	2025-05-01 10:04:56	1	8	compra
73	\N	2	13	ingreso	12.00	12.00	144.00	2025-05-01 10:04:56	1	8	compra
74	\N	2	8	ingreso	222.00	12.00	2664.00	2025-05-01 10:06:35	1	9	compra
75	\N	2	13	ingreso	122.00	12.00	1464.00	2025-05-01 10:06:35	1	9	compra
76	\N	2	12	ingreso	12.00	121.00	1452.00	2025-05-01 10:07:04	1	10	compra
77	\N	2	9	egreso	-3.00	0.00	0.00	2025-05-01 10:08:25	1	10	produccion
78	\N	2	10	egreso	-6.00	0.00	0.00	2025-05-01 10:08:25	1	10	produccion
79	\N	2	11	egreso	-6.00	0.00	0.00	2025-05-01 10:08:25	1	10	produccion
80	\N	2	12	egreso	-12.00	0.00	0.00	2025-05-01 10:08:25	1	10	produccion
81	\N	5	2	ingreso	75.00	0.00	0.00	2025-05-01 10:08:25	1	10	produccion
82	\N	2	8	egreso	-12.00	0.00	0.00	2025-05-01 10:10:51	1	11	produccion
83	\N	2	9	egreso	-12.00	0.00	0.00	2025-05-01 10:10:51	1	11	produccion
84	\N	2	10	egreso	-4.00	0.00	0.00	2025-05-01 10:10:51	1	11	produccion
85	\N	2	12	egreso	-16.00	0.00	0.00	2025-05-01 10:10:51	1	11	produccion
86	\N	4	5	ingreso	88.00	0.00	0.00	2025-05-01 10:10:51	1	11	produccion
87	\N	3	2	egreso	-5.00	0.10	-0.50	2025-05-01 10:13:55	1	12	venta
88	\N	5	5	egreso	-5.00	8.00	-40.00	2025-05-01 10:16:05	1	13	venta
89	\N	2	10	traspaso_origen	-10.00	0.00	0.00	2025-05-01 13:10:11	1	2	traspaso
90	\N	4	10	traspaso_destino	10.00	0.00	0.00	2025-05-01 13:10:11	1	2	traspaso
91	\N	2	10	traspaso_origen	-10.00	12.00	-120.00	2025-05-01 13:10:11	1	2	traspaso
92	\N	4	10	traspaso_destino	10.00	12.00	120.00	2025-05-01 13:10:11	1	2	traspaso
93	\N	2	8	egreso	-2.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
94	\N	2	9	egreso	-3.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
95	\N	2	10	egreso	-1.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
96	\N	2	11	egreso	-1.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
97	\N	2	12	egreso	-5.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
98	\N	5	3	ingreso	21.00	0.00	0.00	2025-05-01 16:48:54	1	12	produccion
99	\N	2	8	egreso	-5.00	0.00	0.00	2025-05-01 16:53:15	1	14	produccion
100	\N	2	9	egreso	-3.00	0.00	0.00	2025-05-01 16:53:15	1	14	produccion
101	\N	2	10	egreso	-5.00	0.00	0.00	2025-05-01 16:53:15	1	14	produccion
102	\N	6	7	ingreso	5.00	0.00	0.00	2025-05-01 16:53:15	1	14	produccion
103	\N	2	8	egreso	-5.00	0.00	0.00	2025-05-01 16:53:44	1	13	produccion
104	\N	2	9	egreso	-3.00	0.00	0.00	2025-05-01 16:53:44	1	13	produccion
105	\N	2	10	egreso	-5.00	0.00	0.00	2025-05-01 16:53:44	1	13	produccion
106	\N	5	7	ingreso	5.00	0.00	0.00	2025-05-01 16:53:44	1	13	produccion
107	\N	2	13	ingreso	123.00	23.00	2829.00	2025-05-01 17:00:29	1	11	compra
108	\N	2	14	ingreso	321.00	12.00	3852.00	2025-05-01 17:07:29	1	12	compra
109	55	3	2	Consumo	-1.00	0.00	0.00	2026-07-07 13:13:45.459709	1	14	Venta
110	53	3	3	Consumo	-1.00	0.00	0.00	2026-07-07 13:28:43.281501	1	15	Venta
111	79	2	12	Ingreso	4.00	3.30	13.20	2026-07-07 13:42:24.918565	1	5	Compra
112	53	3	3	Consumo	-1.00	0.00	0.00	2026-07-07 13:51:45.330884	1	16	Venta
113	57	3	6	Salida Traspaso	-20.00	0.00	0.00	2026-07-07 18:21:18.026793	1	\N	\N
114	70	5	2	Salida Traspaso	-25.00	0.00	0.00	2026-07-07 18:22:12.570408	1	\N	\N
115	74	5	3	Consumo	-21.00	0.00	0.00	2026-07-07 21:08:40.6631	1	17	Venta
117	76	5	7	Consumo	-5.00	0.00	0.00	2026-07-07 21:30:05.258654	1	20	Venta
118	82	2	8	Ingreso	22.00	1.40	30.80	2026-07-07 21:45:42.106581	1	6	Compra
119	83	2	9	Ingreso	10.00	83.30	833.00	2026-07-08 01:45:26.527277	1	7	Compra
120	55	3	2	Consumo	-9.00	0.00	0.00	2026-07-08 01:46:16.445151	1	21	Venta
121	46	2	8	Consumo	-2.00	12.00	-24.00	2026-07-08 01:51:15.52935	1	17	Producción
122	52	2	12	Consumo	-2.00	5.98	-11.96	2026-07-08 01:51:15.585147	1	17	Producción
123	84	2	4	Ingreso	20.00	0.00	0.00	2026-07-08 01:51:15.636321	1	17	Producción
124	81	6	2	Salida Traspaso	-20.00	0.00	0.00	2026-07-08 12:08:46.243551	1	\N	\N
125	48	2	10	Salida Traspaso	-10.00	1.00	-10.00	2026-07-08 13:56:08.874675	1	\N	\N
126	46	2	8	Consumo	-4.00	12.00	-48.00	2026-07-08 14:52:46.709007	3	18	Producción
127	52	2	12	Consumo	-4.00	5.98	-23.92	2026-07-08 14:52:46.769755	3	18	Producción
128	87	3	4	Ingreso	40.00	0.00	0.00	2026-07-08 14:52:46.846553	3	18	Producción
129	88	2	14	Ingreso	100.00	15.00	1500.00	2026-07-08 16:54:06.108567	1	8	Compra
130	84	2	4	Consumo	-2.00	0.00	0.00	2026-07-08 16:54:29.434254	1	22	Venta
131	85	2	2	Consumo	-2.00	0.00	0.00	2026-07-08 16:54:29.698209	1	22	Venta
132	47	2	9	Salida Traspaso	-22.00	32.00	-704.00	2026-07-08 16:54:59.079464	1	\N	\N
133	53	3	3	Consumo Global (Venta)	-2.00	0.00	0.00	2026-07-08 17:16:07.420867	1	23	Venta
134	53	3	3	Consumo Global (Venta)	-1.00	0.00	0.00	2026-07-08 17:55:14.26708	1	26	Venta
135	55	3	2	Consumo Global (Venta)	-1.00	0.00	0.00	2026-07-08 18:01:21.085698	1	27	Venta
136	51	3	4	Consumo Global (Venta)	-4.00	0.00	0.00	2026-07-08 18:01:43.410285	1	28	Venta
137	90	1	8	Ingreso	10.00	18.50	185.00	2026-07-08 18:02:09.441916	1	9	Compra
138	46	2	8	Consumo	-4.00	12.00	-48.00	2026-07-08 18:03:26.949064	3	19	Producción
139	52	2	12	Consumo	-4.00	5.98	-23.92	2026-07-08 18:03:27.006219	3	19	Producción
140	91	3	4	Ingreso	40.00	0.00	0.00	2026-07-08 18:03:27.078237	3	19	Producción
141	46	2	8	Consumo	-2.00	12.00	-24.00	2026-07-08 21:25:00.654714	4	20	Producción
142	52	2	12	Consumo	-2.00	5.98	-11.96	2026-07-08 21:25:00.737271	4	20	Producción
143	92	5	4	Ingreso	20.00	0.00	0.00	2026-07-08 21:25:00.785313	4	20	Producción
144	55	3	2	Salida Traspaso	-1.00	0.00	0.00	2026-07-08 22:41:12.992637	1	\N	\N
\.


--
-- Data for Name: traspasos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.traspasos (id_traspaso, id_almacen_origen, id_almacen_destino, id_empleado, fecha_solicitud, fecha_aprobacion, estado, observaciones) FROM stdin;
1	2	4	1	2025-05-01 00:00:00	2025-05-01 00:00:00	completado	traspaso
2	6	2	1	2026-07-08 12:08:46.277494	\N	Completado	hj
3	2	4	1	2026-07-08 13:56:08.907007	\N	Completado	dass
4	2	4	1	2026-07-08 16:54:59.079775	\N	Completado	doc
5	3	1	1	2026-07-08 22:41:13.041654	\N	Completado	dsfa
\.


--
-- Data for Name: traspasos_almacen_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.traspasos_almacen_item (id_traspaso_item, id_traspaso, id_item, cantidad, id_lote_origen, id_lote_destino) FROM stdin;
1	1	10	10.00	\N	\N
2	2	2	20.00	\N	\N
3	3	10	10.00	48	86
4	4	9	22.00	47	89
5	5	2	1.00	55	93
\.


--
-- Name: lotes_inventario_id_lote_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lotes_inventario_id_lote_seq', 93, true);


--
-- Name: movimientos_inventario_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_inventario_id_movimiento_seq', 144, true);


--
-- Name: traspasos_almacen_item_id_traspaso_item_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.traspasos_almacen_item_id_traspaso_item_seq', 5, true);


--
-- Name: traspasos_id_traspaso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.traspasos_id_traspaso_seq', 5, true);


--
-- Name: configuracion_inventario PK_configuracion_inventario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracion_inventario
    ADD CONSTRAINT "PK_configuracion_inventario" PRIMARY KEY (clave);


--
-- Name: lotes_inventario PK_lotes_inventario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lotes_inventario
    ADD CONSTRAINT "PK_lotes_inventario" PRIMARY KEY (id_lote);


--
-- Name: movimientos_inventario PK_movimientos_inventario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos_inventario
    ADD CONSTRAINT "PK_movimientos_inventario" PRIMARY KEY (id_movimiento);


--
-- Name: traspasos PK_traspasos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.traspasos
    ADD CONSTRAINT "PK_traspasos" PRIMARY KEY (id_traspaso);


--
-- Name: traspasos_almacen_item PK_traspasos_almacen_item; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.traspasos_almacen_item
    ADD CONSTRAINT "PK_traspasos_almacen_item" PRIMARY KEY (id_traspaso_item);


--
-- PostgreSQL database dump complete
--

\unrestrict 9ZPc05UOAFTfj5TJf47h9EQWn0DMCBr0JtPmIBHjpxlbHxfMgZ5jRpcyfLn8Rg0

--
-- Database "db_security" dump
--

--
-- PostgreSQL database dump
--

\restrict F4jzwDqPDIjoj9I9Ch2ZIdqGo4f2HeYgKIiQdmXkfbLxB8TFhKG09N3Ggeh5yjH

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: db_security; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_security WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE db_security OWNER TO postgres;

\unrestrict F4jzwDqPDIjoj9I9Ch2ZIdqGo4f2HeYgKIiQdmXkfbLxB8TFhKG09N3Ggeh5yjH
\connect db_security
\restrict F4jzwDqPDIjoj9I9Ch2ZIdqGo4f2HeYgKIiQdmXkfbLxB8TFhKG09N3Ggeh5yjH

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Empleado" (
    id_empleado integer NOT NULL,
    nombre character varying(100),
    apellido character varying(100),
    telefono character varying(50),
    direccion character varying(255),
    fecha_nac timestamp without time zone,
    sueldo numeric(18,2),
    edad integer
);


ALTER TABLE public."Empleado" OWNER TO postgres;

--
-- Name: Empleado_id_empleado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Empleado_id_empleado_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Empleado_id_empleado_seq" OWNER TO postgres;

--
-- Name: Empleado_id_empleado_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Empleado_id_empleado_seq" OWNED BY public."Empleado".id_empleado;


--
-- Name: Permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Permiso" (
    "ID_Permiso" integer NOT NULL,
    "Nombre_Permiso" character varying(50) NOT NULL,
    "Descripcion" character varying(255),
    "Fecha_Creacion" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public."Permiso" OWNER TO postgres;

--
-- Name: Permiso_ID_Permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Permiso_ID_Permiso_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Permiso_ID_Permiso_seq" OWNER TO postgres;

--
-- Name: Permiso_ID_Permiso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Permiso_ID_Permiso_seq" OWNED BY public."Permiso"."ID_Permiso";


--
-- Name: Rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rol" (
    "ID_Rol" integer NOT NULL,
    "Nombre_Rol" character varying(50) NOT NULL,
    "Descripcion" character varying(255),
    "Fecha_Creacion" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public."Rol" OWNER TO postgres;

--
-- Name: Rol_ID_Rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Rol_ID_Rol_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Rol_ID_Rol_seq" OWNER TO postgres;

--
-- Name: Rol_ID_Rol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Rol_ID_Rol_seq" OWNED BY public."Rol"."ID_Rol";


--
-- Name: Rol_Permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rol_Permiso" (
    "ID_Rol_Permiso" integer NOT NULL,
    "ID_Rol" integer NOT NULL,
    "ID_Permiso" integer NOT NULL
);


ALTER TABLE public."Rol_Permiso" OWNER TO postgres;

--
-- Name: Rol_Permiso_ID_Rol_Permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Rol_Permiso_ID_Rol_Permiso_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Rol_Permiso_ID_Rol_Permiso_seq" OWNER TO postgres;

--
-- Name: Rol_Permiso_ID_Rol_Permiso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Rol_Permiso_ID_Rol_Permiso_seq" OWNED BY public."Rol_Permiso"."ID_Rol_Permiso";


--
-- Name: Rol_Permiso_Usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rol_Permiso_Usuario" (
    "ID_Usuario_Rol_Permiso" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ID_Rol_Permiso" integer NOT NULL
);


ALTER TABLE public."Rol_Permiso_Usuario" OWNER TO postgres;

--
-- Name: Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq" OWNER TO postgres;

--
-- Name: Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq" OWNED BY public."Rol_Permiso_Usuario"."ID_Usuario_Rol_Permiso";


--
-- Name: Usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuario" (
    "UserId" integer NOT NULL,
    "Fullname" character varying(255) NOT NULL,
    "Username" character varying(50) NOT NULL,
    "Password" character varying(50) NOT NULL,
    id_empleado integer,
    id_cliente integer
);


ALTER TABLE public."Usuario" OWNER TO postgres;

--
-- Name: Usuario_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Usuario_UserId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Usuario_UserId_seq" OWNER TO postgres;

--
-- Name: Usuario_UserId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Usuario_UserId_seq" OWNED BY public."Usuario"."UserId";


--
-- Name: Empleado id_empleado; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Empleado" ALTER COLUMN id_empleado SET DEFAULT nextval('public."Empleado_id_empleado_seq"'::regclass);


--
-- Name: Permiso ID_Permiso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Permiso" ALTER COLUMN "ID_Permiso" SET DEFAULT nextval('public."Permiso_ID_Permiso_seq"'::regclass);


--
-- Name: Rol ID_Rol; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol" ALTER COLUMN "ID_Rol" SET DEFAULT nextval('public."Rol_ID_Rol_seq"'::regclass);


--
-- Name: Rol_Permiso ID_Rol_Permiso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso" ALTER COLUMN "ID_Rol_Permiso" SET DEFAULT nextval('public."Rol_Permiso_ID_Rol_Permiso_seq"'::regclass);


--
-- Name: Rol_Permiso_Usuario ID_Usuario_Rol_Permiso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso_Usuario" ALTER COLUMN "ID_Usuario_Rol_Permiso" SET DEFAULT nextval('public."Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq"'::regclass);


--
-- Name: Usuario UserId; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario" ALTER COLUMN "UserId" SET DEFAULT nextval('public."Usuario_UserId_seq"'::regclass);


--
-- Data for Name: Empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Empleado" (id_empleado, nombre, apellido, telefono, direccion, fecha_nac, sueldo, edad) FROM stdin;
1	Admin	Sistema	123456	Calle	1990-01-01 00:00:00	1000.00	30
3	Admin	Otto	12345678	Panaderia	\N	\N	\N
4	Dennis	Otto	12345678	Panaderia	\N	\N	\N
5	Compra	Otto	12345678	Panaderia	\N	\N	\N
6	Produccion	Otto	12345678	Panaderia	\N	\N	\N
7	Empleado	Otto	12345678	Panaderia	\N	\N	\N
8	mario	castellano	21321	\N	\N	12.00	\N
\.


--
-- Data for Name: Permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Permiso" ("ID_Permiso", "Nombre_Permiso", "Descripcion", "Fecha_Creacion") FROM stdin;
1	Usuario	Gestión de usuarios en el sistema	2026-07-07 20:24:53.278786
2	Rol	Gestión de roles de seguridad	2026-07-07 20:24:53.278786
3	Rol Permiso	Asignación de permisos a roles	2026-07-07 20:24:53.278786
4	Asignacion Roles y Permisos	Asignar roles y permisos a usuarios	2026-07-07 20:24:53.278786
5	Cliente	Gestión de clientes	2026-07-07 20:24:53.278786
6	Items	Gestión de items (productos, insumos y categorías)	2026-07-07 20:24:53.278786
7	Almacen	Gestión de almacenes	2026-07-07 20:24:53.278786
8	Producto Almacen	Asignar productos/insumos a almacén	2026-07-07 20:24:53.278786
9	Venta	Gestión de ventas	2026-07-07 20:24:53.278786
10	Proveedor	Gestión de proveedores de compras	2026-07-07 20:24:53.278786
11	Nota Compra	Gestión de notas de compra	2026-07-07 20:24:53.278786
12	Produccion	Gestión de recetas y tablero de producción	2026-07-07 20:24:53.278786
13	Lotes Inventario	Visualizar y gestionar lotes de inventario	2026-07-07 20:24:53.278786
14	Movimientos	Ver historial de movimientos de inventario	2026-07-07 20:24:53.278786
15	Traspasos	Registrar traspasos entre almacenes	2026-07-07 20:24:53.278786
16	Configuracion Inventario	Configuración de parámetros de inventario	2026-07-07 20:24:53.278786
17	Reportes	Acceso al dashboard de reportes y métricas	2026-07-07 20:24:53.278786
\.


--
-- Data for Name: Rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Rol" ("ID_Rol", "Nombre_Rol", "Descripcion", "Fecha_Creacion") FROM stdin;
1	Administrador	Rol con privilegios completos para gestionar usuarios y configuraciones del sistema.	2026-07-07 20:24:53.276799
2	Encargado ventas	Rol encargado de gestionar las ventas, los clientes y el inventario relacionado.	2026-07-07 20:24:53.276799
3	Encargado compras	Rol encargado de gestionar las compras, proveedores e inventario.	2026-07-07 20:24:53.276799
4	Encargado produccion	Rol encargado de gestionar recetas, tablero de producción e inventario.	2026-07-07 20:24:53.276799
5	Empleado basico	Acceso básico de visualización e inventario.	2026-07-07 20:24:53.276799
\.


--
-- Data for Name: Rol_Permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Rol_Permiso" ("ID_Rol_Permiso", "ID_Rol", "ID_Permiso") FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	7
8	1	8
9	1	9
10	1	10
11	1	11
12	1	12
13	1	13
14	1	14
15	1	15
16	1	16
17	1	17
18	2	5
19	2	6
20	2	7
21	2	8
22	2	9
23	2	13
24	2	14
25	2	15
27	3	7
28	3	10
29	3	11
30	3	13
31	3	14
32	3	15
33	4	6
34	4	7
35	4	12
36	4	13
37	4	14
38	4	15
39	5	7
40	5	13
41	5	14
42	5	15
43	3	6
\.


--
-- Data for Name: Rol_Permiso_Usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Rol_Permiso_Usuario" ("ID_Usuario_Rol_Permiso", "UserId", "ID_Rol_Permiso") FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	7
8	1	8
9	1	9
10	1	10
11	1	11
12	1	12
13	1	13
14	1	14
15	1	15
16	1	16
17	1	17
18	2	18
19	2	19
20	2	20
21	2	21
22	2	22
23	2	23
24	2	24
25	2	25
26	3	39
27	3	40
28	3	41
29	3	42
30	4	1
31	4	2
32	4	3
33	4	4
34	4	5
35	4	6
36	4	7
37	4	8
38	4	9
39	4	10
40	4	11
41	4	12
42	4	13
43	4	14
44	4	15
45	4	16
46	4	17
47	5	1
48	5	2
49	5	3
50	5	4
51	5	5
52	5	6
53	5	7
54	5	8
55	5	9
56	5	10
57	5	11
58	5	12
59	5	13
60	5	14
61	5	15
62	5	16
63	5	17
64	6	1
65	6	2
66	6	3
67	6	4
68	6	5
69	6	6
70	6	7
71	6	8
72	6	9
73	6	10
74	6	11
75	6	12
76	6	13
77	6	14
78	6	15
79	6	16
80	6	17
88	8	33
89	8	34
90	8	35
91	8	36
92	8	37
93	8	38
94	9	39
95	9	40
96	9	41
97	9	42
113	7	27
114	7	29
115	7	31
116	7	30
117	7	32
125	10	16
126	10	2
127	10	1
124	10	17
128	10	3
\.


--
-- Data for Name: Usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Usuario" ("UserId", "Fullname", "Username", "Password", id_empleado, id_cliente) FROM stdin;
1	Edwin Calle	edwincalle	ect*123	\N	\N
2	Carlos Gomez	carlosgomez	cga*456	\N	\N
3	Carlos Ruiz	carlosruiz	password789	\N	\N
4	Admin User	admin@panaderia-otto.shop	K8yB9tZq4MvP3wxR	1	\N
6	Dennis User	dennis@panaderia-otto.shop	A6y3PNfyWT9dkhp/	4	\N
8	Produccion User	produccion@panaderia-otto.shop	Qvu3t0zkpmDfYN+T	6	\N
9	Empleado User	empleado@panaderia-otto.shop	hY5e3qYBrtFlE/h7	7	\N
11	lizt sss	sa@gmail.com	K8yB9tZq4MvP3wxR	\N	6
12	malva visco	malva@gmail.com	K8yB9tz_q4MvP3wxR	\N	7
5	Admin User	admin@panaderia-otto.shop	contraseña	3	\N
10	db	mongo	manzana	8	\N
7	Compra User	compra@panaderia-otto.shop	Compas123	5	\N
\.


--
-- Name: Empleado_id_empleado_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Empleado_id_empleado_seq"', 8, true);


--
-- Name: Permiso_ID_Permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Permiso_ID_Permiso_seq"', 17, true);


--
-- Name: Rol_ID_Rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Rol_ID_Rol_seq"', 5, true);


--
-- Name: Rol_Permiso_ID_Rol_Permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Rol_Permiso_ID_Rol_Permiso_seq"', 43, true);


--
-- Name: Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Rol_Permiso_Usuario_ID_Usuario_Rol_Permiso_seq"', 128, true);


--
-- Name: Usuario_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Usuario_UserId_seq"', 12, true);


--
-- Name: Empleado Empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Empleado"
    ADD CONSTRAINT "Empleado_pkey" PRIMARY KEY (id_empleado);


--
-- Name: Permiso Permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Permiso"
    ADD CONSTRAINT "Permiso_pkey" PRIMARY KEY ("ID_Permiso");


--
-- Name: Rol_Permiso_Usuario Rol_Permiso_Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso_Usuario"
    ADD CONSTRAINT "Rol_Permiso_Usuario_pkey" PRIMARY KEY ("ID_Usuario_Rol_Permiso");


--
-- Name: Rol_Permiso Rol_Permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso"
    ADD CONSTRAINT "Rol_Permiso_pkey" PRIMARY KEY ("ID_Rol_Permiso");


--
-- Name: Rol Rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol"
    ADD CONSTRAINT "Rol_pkey" PRIMARY KEY ("ID_Rol");


--
-- Name: Usuario Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT "Usuario_pkey" PRIMARY KEY ("UserId");


--
-- Name: Rol_Permiso fk_rolpermiso_permiso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso"
    ADD CONSTRAINT fk_rolpermiso_permiso FOREIGN KEY ("ID_Permiso") REFERENCES public."Permiso"("ID_Permiso") ON DELETE CASCADE;


--
-- Name: Rol_Permiso fk_rolpermiso_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso"
    ADD CONSTRAINT fk_rolpermiso_rol FOREIGN KEY ("ID_Rol") REFERENCES public."Rol"("ID_Rol") ON DELETE CASCADE;


--
-- Name: Rol_Permiso_Usuario fk_rpu_rolpermiso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso_Usuario"
    ADD CONSTRAINT fk_rpu_rolpermiso FOREIGN KEY ("ID_Rol_Permiso") REFERENCES public."Rol_Permiso"("ID_Rol_Permiso") ON DELETE CASCADE;


--
-- Name: Rol_Permiso_Usuario fk_rpu_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rol_Permiso_Usuario"
    ADD CONSTRAINT fk_rpu_usuario FOREIGN KEY ("UserId") REFERENCES public."Usuario"("UserId") ON DELETE CASCADE;


--
-- Name: Usuario fk_usuario_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT fk_usuario_empleado FOREIGN KEY (id_empleado) REFERENCES public."Empleado"(id_empleado) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict F4jzwDqPDIjoj9I9Ch2ZIdqGo4f2HeYgKIiQdmXkfbLxB8TFhKG09N3Ggeh5yjH

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict miQNhOTfSz9s4ALH77weAq23USEDC8pE662P23pnmHRLpBZk9qiHiWAoxXZyaue

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict miQNhOTfSz9s4ALH77weAq23USEDC8pE662P23pnmHRLpBZk9qiHiWAoxXZyaue

--
-- PostgreSQL database cluster dump complete
--

