// <auto-generated />
using System;
using MSVenta.Inventario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MSVenta.Inventario.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260615224557_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MSVenta.Inventario.Models.ConfiguracionInventario", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Clave");

                    b.ToTable("configuracion_inventario");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.LoteInventario", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lote")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad_disponible");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_salida");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<string>("MetodoValuacion")
                        .HasColumnType("text")
                        .HasColumnName("metodo_valuacion");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasColumnType("text")
                        .HasColumnName("referencia_tipo");

                    b.HasKey("IdLote");

                    b.ToTable("lotes_inventario");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_total");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<int?>("IdLote")
                        .HasColumnType("integer")
                        .HasColumnName("id_lote");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasColumnType("text")
                        .HasColumnName("referencia_tipo");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("text")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdMovimiento");

                    b.ToTable("movimientos_inventario");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Traspaso", b =>
                {
                    b.Property<int>("IdTraspaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_traspaso")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdAlmacenDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen_destino");

                    b.Property<int>("IdAlmacenOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen_origen");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTraspaso");

                    b.ToTable("traspasos");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.TraspasoAlmacenItem", b =>
                {
                    b.Property<int>("IdTraspasoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_traspaso_item")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<int>("IdTraspaso")
                        .HasColumnType("integer")
                        .HasColumnName("id_traspaso");

                    b.HasKey("IdTraspasoItem");

                    b.ToTable("traspasos_almacen_item");
                });
#pragma warning restore 612, 618
        }
    }
}
